[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  GROQ_API_KEY = "YOUR_GROQ_API_KEY_HERE"

[[edge_functions]]
  function = "groq-api"
  path = "/api/groq"